### ISSUE TITLE
Unable to select maxDate date

### ISSUE THREAD

**Issue by rkrater** [Vuepic/vue-datepicker#124]
**Describe the bug**
I'm unable to select the last date when I set the minDate & maxDate. The maxDate date isn't grayed out just nothing happens when you click it. `internalModelChange` emits the date but `update:modelValue` is not emitted.

**To Reproduce**
````javascript
<Datepicker
ref="picker"
:class="{ 'is-invalid': errors.date }"
:maxDate="new Date(dates.max)"
:minDate="new Date(dates.min)"
@internalModelChange="handleInternal"
autoApply
format="yyyy-MM-dd"
v-model="form.date"
></Datepicker>
````

**Expected behavior**
v-model is updated when you select the last date.

**Desktop & mobile (please complete the following information):**
 - Browser [chrome]
 - Library version [3.4.6]

**Comment by Jasenkoo** [comment]
@rkrater I've added an option to disable time validation since it is causing the issue you are facing. Your `maxDate` probably has a time lower than the current time which is preventing it from selecting. By using `ignoreTimeValidaion` prop, you can disable the time check and refer only to the date. It should be released today.
