### ISSUE TITLE
Usage of custom icon slot causes unexpected event bubbling

### ISSUE THREAD

**Issue by lephro** [Vuepic/vue-datepicker#321]
vue-datepicker version:  4.2.1

**Describe the bug**
Whenever I try to use the "calendar-icon" or "clock-icon" slot to overwrite the icons, something in the component seems to break silently (or at least behaves weirdly). I'm opening the date picker inside another dialog which has a directive, that is listening for an outside click (events: click or mousedown) to close it. I'm opening the date picker with the teleport prop and everything works fine:

```html
<vue-date-picker v-model="modelValueProxy" :flow="['month', 'day', 'time']" :teleport="true" />
```

Now I use one of the mentioned icon-slots (e.g. like this):
```html
<vue-date-picker v-model="modelValueProxy" :flow="['month', 'day', 'time']" :teleport="true">
    <template #calendar-icon>
      <v-icon class="ml-2" icon="mdi-calendar-blank" />
    </template>
  </vue-date-picker>
```
The picker-dialog opens (with the month-picker, as it should), but immediatly closes after you select (click) on any month.
I can see that the clickoutside of my outter dialog triggers (it doesnt when the slot is not set). 

I've attached  a screenshot of the event-timelines (with and without the slot), which might describe my problem better. 
![vue-date-picker_icon-slot](https://user-images.githubusercontent.com/40739111/226079278-c0bc0f1f-9d78-4628-8178-4e4a2370eba9.png)

(Left with the default icon / Right with the "calendar-icon" slot)

**Comment by Jasenkoo** [comment]
It is known that when using `teleport`  with a custom click outside directive doesn't play well. What you can do is to try converting an icon into a functional component like [here](https://github.com/Vuepic/vue-datepicker/blob/main/src/VueDatePicker/components/Icons/CalendarIcon.ts) and provide the component instead of an icon or if you have the event available, try to ignore the one coming from the icon element.

**Comment by Jasenkoo** [comment]
I might be able to fix this
