### ISSUE TITLE
The date- and time picker are inconsistent, when setting the `timezone` and `min-date`

### ISSUE THREAD

**Issue by santor** [Vuepic/vue-datepicker#642]
**Describe the bug**
If the `timezone` is set and `min-date` property is given as an ISO string with hours and minutes, the time picker respects it correctly. But the date picker has the date disabled. Without the `timezone` property both are working. 

**To Reproduce**
```
      <Datepicker
        v-model="form.values.startDateTime"
        text-input
        auto-apply
        :timezone="'America/New_York'"
        time-picker-inline
        :format="currentDateFormat"
        :min-date="'2023-11-08T13:23'"
      ></Datepicker>
```

Logs:
```
current local:  Wed Nov 08 2023 18:53:30 GMT+0100 (Central European Standard Time)
current utc:  2023-11-08T17:53:30.302Z
datePicker initial:  2023-11-08T18:23:00.000Z
timeZone:  America/New_York (EST)
minDate:  2023-11-08T13:23
```

**Expected behavior**
The date- and time picker, should both respect the `min-date` if the time is included in the property.

**Screenshots**
<img width="1121" alt="mindate" src="https://github.com/Vuepic/vue-datepicker/assets/3255198/be4cd184-b902-4eef-a12b-060a266d1b90">

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome 118.0.5993.117 (arm64)
 - Library version 7.2.2

**Comment by wesgood** [comment]
Hello, my apologies for commenting on something marked completed so long ago but I have run into the same problem and I think the library supports it but I can't get it to behave.

My picker is for date-time and I don't want to select a value in the past. My form has a timezone selector for users to choose which local time to enter, which gets passed through to the picker via `:timezone` and this appears to work well. The value is parsed in the preferred timezone and gets saved in UTC normally.

I set the `:min-date` as `new Date()`. Whenever choosing a timezone west (behind me in Eastern time), I can no longer choose today's date as a value. I have tried assigning min-date in the provided timezone, I've tried UTC, string values, Date objects and nothing seems to stay current.

Do you have any suggestions so that I can select today's date when using a timezone?
