### ISSUE TITLE
Calendar select button is disabled on "max-date"

### ISSUE THREAD

**Issue by rrubio** [Vuepic/vue-datepicker#652]
Hi Guys,

I'm using NuxtJS3 and making use of the min-date and max-date. The days show as expected and i am able to click on them, however, on the max-date, the select button is disabled. Any idea why this could be happening? See screenshot below.

Code
```
<VueDatePicker v-model="date" :disabled-week-days="[6, 0]" :min-date="minDate" :max-date="maxDate"></VueDatePicker>
```

Version - 

Vue-datepicker

```
"@vuepic/vue-datepicker": "^7.2.2",
```

NuxtJS3 

```
"nuxt": "^3.7.4",
```

Screenshot - 
<img width="271" alt="vue-datepicker-max-date-disabled" src="https://github.com/Vuepic/vue-datepicker/assets/4221574/9b2c900f-0342-471e-afed-3c01a8871c47">

**Comment by rrubio** [comment]
PS - i've been able to reproduce the error on the playground too, see attached.
<img width="1666" alt="vue-datepicker-playground" src="https://github.com/Vuepic/vue-datepicker/assets/4221574/e26a1493-9011-4936-ae6e-f9bc92e7c00d">

**Comment by AloisSeckar** [comment]
`max-date` has to be passed like this to make it work correctly: `:max-date="new Date('2023-11-24 23:59:59')"`

When `'2023-11-24'` is passed, it only allows me to pick times between `00:00` and `01:00` on that day. I believe this might be because of the timezone offset (I live in GMT+1). 

Anyway I think this is a bug to be solved or a behaviour to be pointed out in the docs.

**Comment by rrubio** [comment]
Thank you @AloisSeckar , that did the trick. I agree with you, seems like a bug to me too.

**Comment by Jasenkoo** [comment]
As @AloisSeckar, min and max dates do affect time.
