### ISSUE TITLE
Quarter picker: selected quarters not highlighted

### ISSUE THREAD

**Issue by Coelmount** [Vuepic/vue-datepicker#678]
**Describe the bug**
When using vue-datepicker in quarter-mode, the selected quarters don't get highlighted, neither in range nor in single quarter selection mode. Only the text in the first and the last month gets the primary-text-color. After investigation, it seems the problem is caused by the fact that I am using tailwind-css as well. Tailwind does some css resets which include a transparent background for buttons. This is overriding the background color set by the css class `dp--qr-btn-active`

Tailwind extract:
```
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/
button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}
```

**To Reproduce**
1. setup a vue-datepicker in a vue project that is using tailwind css
2. configure the datepicker in quarter-mode
3. select a start and end quarter

**Expected behavior**
- First & last quarter had bg-color: dp-primary-color and text color: dp-primary-text-color
- quarters in between have the in-between color

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/26696798/2af9f5e6-da0d-471a-8706-9b2fa72ee884)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version 7.4.0

**Comment by Jasenkoo** [comment]
As you can see on this [playground](https://stackblitz.com/edit/vuepic-vue-datepicker-z6olf7?file=src%2Findex.css,src%2Fmain.js,src%2FApp.vue,src%2Fcomponents%2FPlayground.vue), tailwind has no conflict, just make sure that the date picker CSS file is imported after the tailwind index.css.

For example, in the playground, if you move the CSS import from the component to the `main.js` file above the `index.css` import, the issue is present.
