### ISSUE TITLE
The format() callback argument is not in the correct time zone when the timezone property is set.

### ISSUE THREAD

**Issue by raf59** [Vuepic/vue-datepicker#685]
When I set the timezone, the format() callback argument is not the same as the model value.

```
const test1 = (dates: [Date, Date]) => {
  console.log("formatter");
  console.log(dates[0]);
  return dates[0].toISOString();
};
const test2 = (dates: [Date, Date]) => {
  console.log("model value");
  console.log(dates[0]);
};

///////////

<Datepicker
    timezone="Pacific/Auckland"
    :format="test1"
    @update:model-value="test2"
/>
```

I was expecting the model-value and the format argument to return the same date, but they are different.
The console logs :
![image](https://github.com/Vuepic/vue-datepicker/assets/51642385/3923b5f6-ed95-4074-a39f-171ee2e5c61c)

Did I miss something, or is it a bug?

**Comment by Jasenkoo** [comment]
This is correct behavior, you are receiving the raw date, (in your current timezone), and it will add a bunch of boilerplate code to send the converted date, because the existing logic that does this when emitting `model-value` is validating in addition, meaning, preview value can be an invalid one.
