### ISSUE TITLE
The datepicker menu should jump to the mobile layout earlier depending on the total width of the menu

### ISSUE THREAD

**Issue by BryanKuiper** [Vuepic/vue-datepicker#690]
Hello,

I added a sidebar with multiple presets and use multi-calendars as a range picker.
When I open the datepicker menu it opens partially offscreen when the screen becomes smaller than +/- 740 px. It jumps to the mobile layout at 600 px or lower, but because the text of some presets are longer it should jump to the mobile layout earlier. This also happens when using white-space: nowrap on the sidebar.

When using position: left:
![image](https://github.com/Vuepic/vue-datepicker/assets/30691301/22965002-112e-4edd-82c9-052a2792d3eb)

When using position: right or center:
![image](https://github.com/Vuepic/vue-datepicker/assets/30691301/52b76edf-77cf-4893-bbb1-3b64bc97addb)

https://stackblitz.com/edit/vuepic-vue-datepicker-v2wkgv?file=src%2Fcomponents%2FPlayground.vue

It should calculate when it jumps to a mobile layout when the menu is bigger (keeping margins in mind) than the available width instead of jumping at the fixed 600 px. This would also give users the opportunity to change the style of the menu more freely (larger fonts, more spacing, etc).

Could this solved please? :-)

**Comment by nguyenquocdaile** [comment]
Hi @Jasenkoo , I'm working with multi-calendars too. Could I check that in mobile mode, I just use a single calendar? Because it has a bug that I can't scroll to the Apply and Cannel button below 

Mobile
![image](https://github.com/Vuepic/vue-datepicker/assets/12345613/1ed4f71a-011a-4d73-86fd-56d7d192ee81)

Ipad

![image](https://github.com/Vuepic/vue-datepicker/assets/12345613/7e73951a-7274-4edc-a6b7-91cdd51721cb)
