### ISSUE TITLE
modalValue type and format 

### ISSUE THREAD

**Issue by ljoxloyd** [Vuepic/vue-datepicker#71]
Hello! Amazing library! 

Is there a way for modelValue to be a formatted string instead of Date object?

I can't find it in the documentation, I need functionality similar to what [value-type prop](https://github.com/mengxiong10/vue2-datepicker#value-type) does in vue2-datepicker.

**Comment by Jasenkoo** [comment]
Not possible right now, but can be added.

**Comment by ljoxloyd** [comment]
That would be great, thank you!

**Comment by Jasenkoo** [comment]
Looking good. I already wrote the logic, need to handle some cases. The thing with the custom function is tricky since it may be easy to parse `Date` to `any` but parsing it back to the `Date` object is tricky.  Basically, the format needs to be compatible with `new Date(customValue)` unlike when using timestamps or codes
