### ISSUE TITLE
The date is not displayed based on the timezone prop

### ISSUE THREAD

**Issue by quar7z-cygni** [Vuepic/vue-datepicker#773]
**Describe the bug**
When I set the timezone prop, the date is not displayed based on the timezone prop, it is displayed based on the local client timezone.
This happened on version 8.2.0.
I downgraded to a lower version (5.0.0) and in that case it worked fine.

**Expected behavior**
The date should be displayed based on the timezone prop.

**Screenshots**
![bad](https://github.com/Vuepic/vue-datepicker/assets/39636550/cc52c4a2-f237-40e5-90f1-c4023c90c6c1)
![good](https://github.com/Vuepic/vue-datepicker/assets/39636550/e6a4a718-a859-4fa3-a971-74eb2ee9e75f)

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome, Firefox, ...
 - Library version: 8.2.0

**Comment by Jasenkoo** [comment]
As stated in the changelog for [v8.1.0](https://github.com/Vuepic/vue-datepicker/releases/tag/v8.1.0) converting the `v-model` value based on the timezone is removed

**Comment by 719media** [comment]
Is this decision elaborated  upon anywhere? You mentioned the changelog, and the changelog says what happened, but is there a why?

I'm running into an issue where I want the user to have a defined timezone for purposes of the calendar displaying, and send a different timezone back to the server. This change caused some unexpected behavior that I just don't understand. Now, if the user has a timezone they'd like to view the calendar in, there doesn't seem to be a way to do that, it only works on whatever the browser date timezone is?

**Comment by 719media** [comment]
I've spent several hours reading and testing https://vue3datepicker.com/props/modes-configuration/#timezone-configuration and probably left more confused than when I started.
What, exactly, is the point of timezone? The most obvious thing I would THINK would be that the provided date would be adjusted so that the proper times were selected. For example in the following playground:

https://stackblitz.com/edit/vuepic-vue-datepicker-hessqw?file=src%2Fcomponents%2FPlayground.vue

Changing the "timezone" only appears to affect the calculation of maxDate. But, it doesn't modify the "current time" selected. For example, the hours selection continues to show the hours in the system timezone (in my case, this is America/Los_Angeles), rather than being modified to show in the specified timezone (America/New_York in the codesandbox). It's very confusing that the timezone only affects the calendar calculation of maxDate, but not of the hour selection of a provided date.

It seems like this library is well thought out, which is why I think that I must be missing something, but it appears that having a date like `2024-03-14T02:04:00.000+00:00` and wanting to convert that date to a "timezone" that differs from the system (client) timezone is not supported by this library, can you confirm?

**Comment by quar7z-cygni** [comment]
Yeah, I'm in the same situation.
I don't know if I'm missing something or this is what it is.
I'm using version 7 for now, but I know this is not ideal.

Can you help us with this @Jasenkoo? With a clarification?

**Comment by Jasenkoo** [comment]
@719media @quar7z-cygni I will return the option to convert the `v-model`.

**Comment by quar7z-cygni** [comment]
Thank you @Jasenkoo
