### ISSUE TITLE
Add Buddhist year feature

### ISSUE THREAD

**Issue by gapgag55** [Vuepic/vue-datepicker#8]
Hi team, 

Can you add more features? 
"Buddhist year feature" just plus +543 to the current year or adding yearNameFormating which like monthNameFormat

**Comment by Jasenkoo** [comment]
@gapgag55 You can pass `yearRange` and set the range you need

**Comment by kitisak053** [comment]
> @gapgag55 You can pass `yearRange` and set the range you need

@Jasenkoo  hi! i try this answer. but next year February have 29 day, if  i pass yearRange like the answer, next year 2024 + 543 = 2567 (Buddhist year) it have 28 day it incorrect because when 2024 + 543 = 2567 it is year of (Anno Domini) , can i overwrite year select text from 2024 to 2567 for just showing user select?
