### ISSUE TITLE
Week numbers wrong when used in format.

### ISSUE THREAD

**Issue by hrosb** [Vuepic/vue-datepicker#86]
Thanks for a great date picker 💯. We are starting to use this in a project now.

**Describe the bug**
Week number off by +1 week when using in format. When selecting sundays, its off by +2 weeks (even though start day is monday).
Inside the calender the week numbers are correct.
 
**To Reproduce**
1. Go to https://stackblitz.com/edit/vuepic-vue-datepicker-vcsjpr?file=src%2Fcomponents%2FPlayground.vue
2. Select any day - notice the week number.
3. Notice that the week number both in the preview and the input field is wrong.

**Comment by Jasenkoo** [comment]
@hrosb  Thanks, the datepicker uses [ISO week numbering](https://en.wikipedia.org/wiki/ISO_week_date). To correctly show the numbering, just replace the format with `I` instead of `w`, here is the [demo](https://stackblitz.com/edit/vuepic-vue-datepicker-pecckt?file=src%2Fcomponents%2FPlayground.vue)

**Comment by hrosb** [comment]
Thank you @Jasenkoo 

Maybe consider linking to https://date-fns.org/v2.16.1/docs/format instead of unicode.org in the docs.
The date-fns docs has helpfulp information about ISO weeks and about escaping characters in the format string.
